stages:
  - scmaven
  - scdeploy

server-core-maven-build:
  stage: scmaven
  tags:
    - shell
  script:
    - cd Backend/server_core/servercore/
    - mvn package

server-core-autodeploy:
    stage: scdeploy
    tags:
     - shell
    script:
     - sudo systemctl stop intermon-server
     - cd Backend/server_core/servercore/target/
     - cp servercore-0.9.jar /opt/intermon/server_core.jar
     - sudo systemctl start intermon-server
