stages:
  - scmaven
  - sctest
  - scdeploy
  - wsmaven
  - wsdeploy
  - wabuild
  - wadeploy
  - androidbuild

server-core-maven-build:
  stage: scmaven
  tags:
    - shell
  script:
    - cd Backend/server_core/servercore/
    - mvn package
  artifacts:
    paths:
      - Backend/server_core/servercore/

server-core-autotest:
  stage: sctest
  tags:
    - shell
  script:
    - cd Backend/server_core
    - mvn test

server-core-autodeploy:
    stage: scdeploy
    tags:
     - shell
    script:
     - sudo systemctl stop intermon-server
     - cd Backend/server_core/servercore/target/
     - cp servercore-0.9.jar /opt/intermon/server_core.jar
     - cd ..
     - sudo cp -r src/* /opt/intermon/src
     - sudo systemctl start intermon-server

websocket-module-build:
  stage: wsmaven
  tags:
    - shell
  script:
    - cd Backend/server_core/WebSockets/Server/WebSocketServer
    - mvn package
  artifacts:
    paths:
      - Backend/server_core/WebSockets/Server/WebSocketServer/target/

websocket-module-autodeploy:
  stage: wsdeploy
  tags:
    - shell
  script:
    - sudo systemctl stop intermon-websocket
    - cd Backend/server_core/WebSockets/Server/WebSocketServer/target/
    - cp WebSocketServer-0.0.1-SNAPSHOT.jar /opt/intermon/websocket_server.jar
    - sudo systemctl start intermon-websocket

web-application-build:
    stage: wabuild
    tags:
      - shell
    script:
      - cd Backend/IntermonReact/intermon/
      - yarn install
      - yarn run build
    artifacts:
      paths:
        - Backend/IntermonReact/intermon/build

web-application-deploy:
  stage: wadeploy
  tags:
    - shell
  script:
    - cd Backend/IntermonReact/intermon/
    - sudo rm -rf /var/www/html/intermon/*
    - sudo cp -r build/* /var/www/html/intermon/

android-build:
    image: javiersantos/android-ci:latest
    stage: androidbuild
    before_script:
      - export GRADLE_USER_HOME=`pwd`/.gradle
      - chmod +x ./Frontend/IntermonGame/gradlew
    tags:
      - android
    script:
      - cd Frontend/IntermonGame
      - ./gradlew assemble